### ISSUE TITLE
Ratelimit

### ISSUE THREAD

**Issue by Gatossss** [fedecalendino/alfred-minute-inbox#1]
Are there Ratelimits on the website?

**Comment by fedecalendino** [comment]
Not sure, those must be new. I'll check it out tomorrow.

**Comment by Gatossss** [comment]
it wasn't meant as a bug, just as a question, I apologize for the confusion.

**Comment by fedecalendino** [comment]
Oh right! Each inbox lasts 10 minutes, unless you extend them.
